name: daily-commits

on:
  schedule:
    - cron: '30 17 * * *'   # 11:00 PM IST daily (UTC cron)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make 4-5 small commits
        run: |
          set -e
          COMMITS=$(( (RANDOM % 2) + 4 ))  # 4 ya 5 commits
          for i in $(seq 1 $COMMITS); do
            echo "tick $(date -u '+%Y-%m-%d %H:%M:%S') $RANDOM" >> activity.log
            git add activity.log
            git commit -m "chore(bot): daily tick #$i"
            # thoda gap (5–15 sec) — optional
            sleep $(( (RANDOM % 11) + 5 ))
          done

      - name: Push changes
        run: git push
