name: Scheduled Daily Script

# This workflow is triggered on a schedule.
on:
  schedule:
    # This cron expression means the job will run daily at 17:30 UTC.
    # This corresponds to 11:00 PM (23:00) India Standard Time (IST),
    # as IST is UTC + 5:30.
    - cron: '30 17 * * *'

# Defines the jobs that run in this workflow.
jobs:
  run-and-commit:
    # Runs the job on the latest version of Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up a language environment to run your script.
      # Replace 'node' with 'python', 'ruby', etc., depending on your script.
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Run your custom script.
      # I have updated this path to point to the new script.
      - name: Run the script
        run: |
          echo "Executing daily script..."
          node scripts/update_data.js

      # Step 4: Configure Git and commit any changes made by the script.
      - name: Commit and push changes
        run: |
          git config --global user.name 'Workflow'
          git config --global user.email 'workflow@example.com'
          git add .
          git commit -m "update done" || echo "No changes to commit"
          git push
